# Generated by Django 3.1.2 on 2020-10-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
