# Generated by Django 3.1.2 on 2020-10-13 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='shordescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='aboutmedia/'),
        ),
    ]
