# Generated by Django 3.1.2 on 2020-10-13 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201013_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='shordescription',
        ),
        migrations.AddField(
            model_name='about',
            name='Shortdescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
