# Generated by Django 3.1.2 on 2020-10-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201013_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('designiation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Shortdescription',
            new_name='shortdescription',
        ),
    ]
