# Generated by Django 3.1.2 on 2020-10-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
