# Generated by Django 3.1.2 on 2020-10-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201014_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='designiation',
            new_name='location',
        ),
    ]
